/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminLayout: typeof import('./components/layout/AdminLayout.vue')['default']
    AppFooter: typeof import('./components/layout/AppFooter.vue')['default']
    AppHeader: typeof import('./components/layout/AppHeader.vue')['default']
    AppLayout: typeof import('./components/layout/AppLayout.vue')['default']
    AppSidebar: typeof import('./components/layout/AppSidebar.vue')['default']
    ArticleCard: typeof import('./components/common/ArticleCard.vue')['default']
    ArticleList: typeof import('./components/article/ArticleList.vue')['default']
    ArticleToc: typeof import('./components/article/ArticleToc.vue')['default']
    AuthModal: typeof import('./components/auth/AuthModal.vue')['default']
    ChangePasswordModal: typeof import('./components/user/ChangePasswordModal.vue')['default']
    CommentItem: typeof import('./components/comment/CommentItem.vue')['default']
    CommentSection: typeof import('./components/comment/CommentSection.vue')['default']
    CustomSelect: typeof import('./components/ui/CustomSelect.vue')['default']
    EmptyState: typeof import('./components/common/EmptyState.vue')['default']
    HeroCarousel: typeof import('./components/common/HeroCarousel.vue')['default']
    MarkdownEditor: typeof import('./components/article/MarkdownEditor.vue')['default']
    MarkdownViewer: typeof import('./components/article/MarkdownViewer.vue')['default']
    MobileBottomNav: typeof import('./components/layout/MobileBottomNav.vue')['default']
    MobileNav: typeof import('./components/layout/MobileNav.vue')['default']
    MobileTocPanel: typeof import('./components/article/MobileTocPanel.vue')['default']
    MyInfo: typeof import('./components/common/MyInfo.vue')['default']
    Pagination: typeof import('./components/ui/Pagination.vue')['default']
    RightSidebar: typeof import('./components/layout/RightSidebar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TagBadge: typeof import('./components/common/TagBadge.vue')['default']
    ThemePanel: typeof import('./components/common/ThemePanel.vue')['default']
    ToastContainer: typeof import('./components/common/ToastContainer.vue')['default']
  }
}
