/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/layout/AppFooter.vue')['default']
    AppHeader: typeof import('./components/layout/AppHeader.vue')['default']
    AppSidebar: typeof import('./components/layout/AppSidebar.vue')['default']
    ArticleCard: typeof import('./components/common/ArticleCard.vue')['default']
    ArticleMeta: typeof import('./components/article/ArticleMeta.vue')['default']
    ArticleToc: typeof import('./components/article/ArticleToc.vue')['default']
    ChatRoom: typeof import('./components/common/ChatRoom.vue')['default']
    CustomCursor: typeof import('./components/common/CustomCursor.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    EmptyState: typeof import('./components/common/EmptyState.vue')['default']
    HeroSection: typeof import('./components/common/HeroSection.vue')['default']
    KleeCursor: typeof import('./components/common/KleeCursor.vue')['default']
    MarkdownEditor: typeof import('./components/article/MarkdownEditor.vue')['default']
    MarkdownViewer: typeof import('./components/article/MarkdownViewer.vue')['default']
    MobileNav: typeof import('./components/layout/MobileNav.vue')['default']
    MouseEffects: typeof import('./components/common/MouseEffects.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./components/common/SearchBar.vue')['default']
    TagBadge: typeof import('./components/common/TagBadge.vue')['default']
  }
}
