/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminLayout: typeof import('./components/layout/AdminLayout.vue')['default']
    AppFooter: typeof import('./components/layout/AppFooter.vue')['default']
    AppHeader: typeof import('./components/layout/AppHeader.vue')['default']
    AppLayout: typeof import('./components/layout/AppLayout.vue')['default']
    AppSidebar: typeof import('./components/layout/AppSidebar.vue')['default']
    ArticleCard: typeof import('./components/common/ArticleCard.vue')['default']
    ArticleList: typeof import('./components/article/ArticleList.vue')['default']
    ArticleMeta: typeof import('./components/article/ArticleMeta.vue')['default']
    ArticleToc: typeof import('./components/article/ArticleToc.vue')['default']
    ChangePasswordModal: typeof import('./components/user/ChangePasswordModal.vue')['default']
    CommentItem: typeof import('./components/comment/CommentItem.vue')['default']
    CommentSection: typeof import('./components/comment/CommentSection.vue')['default']
    ConfirmDialog: typeof import('./components/ui/ConfirmDialog.vue')['default']
    CustomCursor: typeof import('./components/common/CustomCursor.vue')['default']
    EmptyState: typeof import('./components/common/EmptyState.vue')['default']
    ErrorState: typeof import('./components/ui/ErrorState.vue')['default']
    GlitchText: typeof import('./components/ui/GlitchText.vue')['default']
    HeroCarousel: typeof import('./components/common/HeroCarousel.vue')['default']
    LeftSidebar: typeof import('./components/layout/LeftSidebar.vue')['default']
    LoadingBlock: typeof import('./components/ui/LoadingBlock.vue')['default']
    MainLayout: typeof import('./components/layout/MainLayout.vue')['default']
    MarkdownEditor: typeof import('./components/article/MarkdownEditor.vue')['default']
    MarkdownViewer: typeof import('./components/article/MarkdownViewer.vue')['default']
    MobileDrawer: typeof import('./components/layout/MobileDrawer.vue')['default']
    MobileNav: typeof import('./components/layout/MobileNav.vue')['default']
    MyInfo: typeof import('./components/common/MyInfo.vue')['default']
    NoiseOverlay: typeof import('./components/ui/NoiseOverlay.vue')['default']
    Pagination: typeof import('./components/ui/Pagination.vue')['default']
    RightSidebar: typeof import('./components/layout/RightSidebar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./components/common/SearchBar.vue')['default']
    TagBadge: typeof import('./components/common/TagBadge.vue')['default']
    Toast: typeof import('./components/ui/Toast.vue')['default']
    ToastContainer: typeof import('./components/common/ToastContainer.vue')['default']
    TypewriterText: typeof import('./components/ui/TypewriterText.vue')['default']
  }
}
